const questions = [
    // Multiple Choice
    { type: "mcq", question: "What type of movement takes place within a fixed space and does not involve traveling?", options: ["Locomotor", "Non-locomotor", "Cardiovascular", "Transitional"], answer: "Non-locomotor" },
    { type: "mcq", question: "Which of the following is considered a Locomotor movement?", options: ["Bending", "Twisting", "Galloping", "Swaying"], answer: "Galloping" },
    { type: "mcq", question: "Which element of dance includes 'Tempo, Duration, and Beat'?", options: ["Space", "Force", "Time", "Dynamics"], answer: "Time" },
    { type: "mcq", question: "The elements 'Pathway, Focus, Shape, Level, and Direction' belong to which core dance component?", options: ["Space", "Time", "Force", "Quality"], answer: "Space" },
    { type: "mcq", question: "Which classification of Philippine Folk Dance depicts funny movements or imitates animals?", options: ["Occupational", "Festival", "Mimic or Imitative", "Courtship or Wedding"], answer: "Mimic or Imitative" },
    { type: "mcq", question: "Which two dances are listed as examples of 'Mimic or Imitative' folk dances?", options: ["Maglalatik and Pagbabayo", "Itik-itik and Tinikling", "Careñosa and Sayaw sa Pag-ibig", "Jotas and Fandangos"], answer: "Itik-itik and Tinikling" },
    { type: "mcq", question: "Which Spanish-influenced dances were integrated into Philippine local communities during colonization?", options: ["Salsa and Rumba", "Breaking and Popping", "Jotas, Fandangos, and Waltzes", "Quickstep and Foxtrot"], answer: "Jotas, Fandangos, and Waltzes" },
    { type: "mcq", question: "Which of the following is considered a 'Smooth/Standard Style' ballroom dance?", options: ["Samba", "Swing", "Cha-Cha-Cha", "Foxtrot"], answer: "Foxtrot" },
    { type: "mcq", question: "Which of the following is considered a 'Latin Style' ballroom dance?", options: ["Viennese Waltz", "Rumba", "Quickstep", "Tango"], answer: "Rumba" },
    { type: "mcq", question: "What dance style incorporates the strong legwork of ballet and the trunk movements of modern dance, emphasizing emotional depth?", options: ["Contemporary Dance", "Cheer Dance", "Street Dance", "Folk Dance"], answer: "Contemporary Dance" },
    { type: "mcq", question: "Which dance style combines cheering, gymnastics, and acrobatic moves (like cartwheels) to motivate sports teams?", options: ["Contemporary Dance", "Breaking", "Cheer Dance", "Festival Dance"], answer: "Cheer Dance" },
    { type: "mcq", question: "Which Hip-Hop style is characterized by sharp, robotic movements?", options: ["House", "Popping", "Locking", "Breaking"], answer: "Popping" },
    { type: "mcq", question: "Which Hip-Hop style features acrobatic moves and floor work?", options: ["Popping", "Locking", "Breaking", "House"], answer: "Breaking" },
    { type: "mcq", question: "'Careñosa' and 'Sayaw sa Pag-ibig' are examples of what type of folk dance?", options: ["Religious/Ceremonial", "Festival", "Courtship or Wedding", "Occupational"], answer: "Courtship or Wedding" },
    { type: "mcq", question: "What non-locomotor skill is described as moving a part of the body around a long axis (usually the head and body)?", options: ["Twisting", "Bending", "Lifting", "Swinging"], answer: "Twisting" },
    { type: "mcq", question: "What locomotor movement involves springing on one foot or both feet and landing on both feet?", options: ["Hopping", "Jumping", "Leaping", "Skipping"], answer: "Jumping" },
    { type: "mcq", question: "Which locomotor movement is done with a step and a hop using the same foot?", options: ["Galloping", "Skipping", "Sliding", "Running"], answer: "Skipping" },
    { type: "mcq", question: "What fundamental position of the arms involves both arms raised overhead?", options: ["1st Position", "2nd Position", "3rd Position", "5th Position"], answer: "5th Position" },
    { type: "mcq", question: "Which movement is a pendular movement occurring below an axis?", options: ["Swaying", "Swinging", "Rotating", "Lifting"], answer: "Swinging" },
    { type: "mcq", question: "Which movement is a pendular movement occurring above an axis?", options: ["Swaying", "Swinging", "Bending", "Twisting"], answer: "Swaying" },

    // True/False
    { type: "tf", question: "Locomotor movements involve changing position and moving from one location to another.", answer: "True" },
    { type: "tf", question: "Stretching and bending are examples of locomotor movements.", answer: "False" },
    { type: "tf", question: "'Force' in dance includes Quality, Energy, and Dynamics.", answer: "True" },
    { type: "tf", question: "Dance is often classified as an art form but never as a sport.", answer: "False" },
    { type: "tf", question: "Philippine ethnic dances are primarily classified into Christian and non-Christian groups.", answer: "True" },
    { type: "tf", question: "'Maglalatik' and 'Pagbabayo' are examples of Occupational dances.", answer: "True" },
    { type: "tf", question: "Festival dances are usually performed to celebrate a good harvest or good fortune.", answer: "True" },
    { type: "tf", question: "Tango is known as a passionate and dramatic dance with sharp movements, originating from Argentine styles.", answer: "True" },
    { type: "tf", question: "The Waltz is a lively, syncopated dance in 4/4 time.", answer: "False" },
    { type: "tf", question: "Hip-Hop dance evolved from the music style introduced during the 1970s.", answer: "True" },
    { type: "tf", question: "Social dances cannot be performed competitively; they are only for entertainment.", answer: "False" },
    { type: "tf", question: "The First Position of the feet involves bringing the heels together while keeping the toes apart.", answer: "True" },
    { type: "tf", question: "The Second Position of the feet involves pointing one foot in front of the other.", answer: "False" },
    { type: "tf", question: "Leaping is defined as springing on one foot and landing on the same foot.", answer: "False" },
    { type: "tf", question: "Galloping is stepping on one foot and cutting with the other, either sideward or forward.", answer: "True" },
    { type: "tf", question: "Sliding is done by gliding on the floor, sideward or forward, using the right and left foot alternately.", answer: "True" },
    { type: "tf", question: "Modern dance is considered more formal and strict than classical ballet.", answer: "False" },
    { type: "tf", question: "Religious or Ceremonial dances overlap with sacred and ecstatic dances.", answer: "True" },
    { type: "tf", question: "Dance releases endorphins, which helps reduce stress and improve mood.", answer: "True" },
    { type: "tf", question: "Folk dance is considered a traditional or ethnic dance that embodies a community's heritage.", answer: "True" },

    // Identification
    { type: "identification", question: "What is the act of straightening or extending any part of the body from the joints?", answer: "Extending" },
    { type: "identification", question: "What locomotor movement requires moving with longer strides and at a faster speed than walking?", answer: "Running" },
    { type: "identification", question: "What specific non-locomotor movement involves elevating a part of the body, usually the arms and legs?", answer: "Lifting" },
    { type: "identification", question: "What locomotor movement involves springing on one foot and landing on the other foot with a wide stride?", answer: "Leaping" },
    { type: "identification", question: "What do you call the movement of the muscles around a joint where two body parts meet (also known as flexing)?", answer: "Bending" },
    { type: "identification", question: "What classification of folk dance characterizes the livelihood or daily work of a certain locality?", answer: "Occupational" },
    { type: "identification", question: "What specific folk dance classification is performed to celebrate good harvest, good fortune, or a community's religion/culture?", answer: "Festival" },
    { type: "identification", question: "What type of ballroom dance usually keeps the couple in one spot on the dance floor and includes the Rumba and Swing?", answer: "Latin" },
    { type: "identification", question: "What hip-hop dance style is characterized by funky, stylized gestures?", answer: "Locking" },
    { type: "identification", question: "What Latin ballroom dance is known for being energetic, rhythmic, and having Brazilian origins?", answer: "Samba" },
    { type: "identification", question: "What Latin ballroom dance is known for lively, syncopated Cuban rhythms?", answer: "Cha-Cha-Cha" },
    { type: "identification", question: "What Smooth style ballroom dance is graceful and flowing, typically danced in 3/4 time?", answer: "Waltz" },
    { type: "identification", question: "What is the general term for a set of partner dances enjoyed both socially and competitively around the world?", answer: "Ballroom" },
    { type: "identification", question: "What dance form is considered a traditional recreational dance of an indigenous society, showing cultural characteristics handed down through generations?", answer: "Folk" },
    { type: "identification", question: "According to the PDFs, what dance element consists of Pathway, Focus, Shape, Level, and Direction?", answer: "Space" },
    { type: "identification", question: "What non-locomotor movement is done by moving a part of the body around an axis (also known as encircling)?", answer: "Rotating" },
    { type: "identification", question: "What classification of Philippine folk dance is usually performed by newlyweds together with their relatives?", answer: "Courtship" },
    { type: "identification", question: "Before the Spaniards and Americans came, what groups of people already had a dance culture of their own in the Philippines?", answer: "Tribes" },
    { type: "identification", question: "What fundamental position of the arms has both arms raised sideways with a graceful curve?", answer: "2nd" },
    { type: "identification", question: "What specific Philippine folk dance classification overlaps with sacred dance and focuses on rituals?", answer: "Ceremonial" }
];
